#ifndef STC3100_REG_H_
#define STC3100_REG_H_

#define SLAVE_ADDRESS (0x70 << 1)

#define REG_MODE (0)

#define REG_MODE_SEL_EXT_CLK_Pos (0)
#define REG_MODE_SEL_EXT_CLK_Msk (0x1U << REG_MODE_SEL_EXT_CLK_Pos)
#define REG_MODE_SEL_EXT_CLK_AUTO (0x0U << REG_MODE_SEL_EXT_CLK_Pos)
#define REG_MODE_SEL_EXT_CLK_EXT (0x1U << REG_MODE_SEL_EXT_CLK_Pos)

#define REG_MODE_GG_RES_Pos (1)
#define REG_MODE_GG_RES_Msk (0x3U << REG_MODE_GG_RES_Pos)
#define REG_MODE_GG_RES_14BITS (0x0U << REG_MODE_GG_RES_Pos)
#define REG_MODE_GG_RES_13BITS (0x1U << REG_MODE_GG_RES_Pos)
#define REG_MODE_GG_RES_12BITS (0x2U << REG_MODE_GG_RES_Pos)

#define REG_MODE_GG_CAL_Pos (3)
#define REG_MODE_GG_CAL_Msk (0x1U << REG_MODE_GG_CAL_Pos)
#define REG_MODE_GG_CAL REG_MODE_GG_CAL_Msk

#define REG_MODE_GG_RUN_Pos (4)
#define REG_MODE_GG_RUN_Msk (0x1U << REG_MODE_GG_RUN_Pos)
#define REG_MODE_GG_RUN REG_MODE_GG_RUN_Msk

#define REG_CTRL (1)

#define REG_CTRL_IO0DATA_Pos (0)
#define REG_CTRL_IO0DATA_Msk (0x1U << REG_CTRL_IO0DATA_Pos)
#define REG_CTRL_IO0DATA_LOW (0x0U << REG_CTRL_IO0DATA_Pos)
#define REG_CTRL_IO0DATA_OPEN (0x1U << REG_CTRL_IO0DATA_Pos)

#define REG_CTRL_GG_RST_Pos (1)
#define REG_CTRL_GG_RST_Msk (0x1U << REG_CTRL_GG_RST_Pos)
#define REG_CTRL_GG_RST REG_CTRL_GG_RST_Msk

#define REG_CTRL_PORDET_Pos (4)
#define REG_CTRL_PORDET_Msk (0x1U << REG_CTRL_PORDET_Pos)
#define REG_CTRL_PORDET_RELEASE (0x0U << REG_CTRL_PORDET_Pos)
#define REG_CTRL_PORDET_SRST (0x1U << REG_CTRL_PORDET_Pos)

#define REG_CHARGE_LOW (2)
#define REG_CHARGE_HIGH (3)

#define REG_VOLTAGE_LOW (8)
#define REG_VOLTAGE_HIGH (9)

#endif /* STC3100_REG_H_ */
