#ifndef TMAG5173_REG_H
#define TMAG5173_REG_H

/* clang-format off */
#define SLAVE_ADDRESS (0x35)

#define DEVICE_CONFIG_1 (0x00)
#define DEVICE_CONFIG_1_RESET_VALUE (0x00U)

#define DEVICE_CONFIG_1_CONV_AVG_Pos (2)
#define DEVICE_CONFIG_1_CONV_AVG_Msk (0x7U << DEVICE_CONFIG_1_CONV_AVG_Pos)
#define DEVICE_CONFIG_1_CONV_AVG_1X (0x0U << DEVICE_CONFIG_1_CONV_AVG_Pos)
#define DEVICE_CONFIG_1_CONV_AVG_2X (0x1U << DEVICE_CONFIG_1_CONV_AVG_Pos)
#define DEVICE_CONFIG_1_CONV_AVG_4X (0x2U << DEVICE_CONFIG_1_CONV_AVG_Pos)
#define DEVICE_CONFIG_1_CONV_AVG_8X (0x3U << DEVICE_CONFIG_1_CONV_AVG_Pos)
#define DEVICE_CONFIG_1_CONV_AVG_16X (0x4U << DEVICE_CONFIG_1_CONV_AVG_Pos)
#define DEVICE_CONFIG_1_CONV_AVG_32X (0x5U << DEVICE_CONFIG_1_CONV_AVG_Pos)

#define DEVICE_CONFIG_2 (0x01)
#define DEVICE_CONFIG_2_RESET_VALUE (0x00U)

#define DEVICE_CONFIG_2_OPERATING_MODE_Pos (0)
#define DEVICE_CONFIG_2_OPERATING_MODE_Msk (0x3U << DEVICE_CONFIG_2_OPERATING_MODE_Pos)
#define DEVICE_CONFIG_2_OPERATING_MODE DEVICE_CONFIG_2_OPERATING_MODE_Msk
#define DEVICE_CONFIG_2_OPERATING_MODE_STANDBY (0x0U << DEVICE_CONFIG_2_OPERATING_MODE_Pos)
#define DEVICE_CONFIG_2_OPERATING_MODE_SLEEP (0x1U << DEVICE_CONFIG_2_OPERATING_MODE_Pos)
#define DEVICE_CONFIG_2_OPERATING_MODE_CONTINUOUS (0x2U << DEVICE_CONFIG_2_OPERATING_MODE_Pos)
#define DEVICE_CONFIG_2_OPERATING_MODE_WAKEUP_AND_SLEEP (0x3U << DEVICE_CONFIG_2_OPERATING_MODE_Pos)

#define DEVICE_CONFIG_2_THR_HYST_Pos (5)
#define DEVICE_CONFIG_2_THR_HYST_Msk (0x7U << DEVICE_CONFIG_2_THR_HYST_Pos)
#define DEVICE_CONFIG_2_THR_HYST_2S_COMPL (0x0U << DEVICE_CONFIG_2_THR_HYST_Pos)
#define DEVICE_CONFIG_2_THR_HYST_OPPOSITE (0x1U << DEVICE_CONFIG_2_THR_HYST_Pos)

#define SENSOR_CONFIG_1 (0x02)
#define SENSOR_CONFIG_1_RESET_VALUE (0x00U)

#define SENSOR_CONFIG_1_SLEEPTIME_Pos (0)
#define SENSOR_CONFIG_1_SLEEPTIME_Msk (0xFU << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_1_MS (0x0U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_5_MS (0x1U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_10_MS (0x2U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_15_MS (0x3U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_20_MS (0x4U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_30_MS (0x5U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_50_MS (0x6U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_100_MS (0x7U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_500_MS (0x8U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_1000_MS (0x9U << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_2000_MS (0xAU << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_5000_MS (0xBU << SENSOR_CONFIG_1_SLEEPTIME_Pos)
#define SENSOR_CONFIG_1_SLEEPTIME_20000_MS (0xCU << SENSOR_CONFIG_1_SLEEPTIME_Pos)

#define SENSOR_CONFIG_1_MAG_CH_EN_Pos (4)
#define SENSOR_CONFIG_1_MAG_CH_EN_Msk (0xFU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_OFF (0x0U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_X (0x1U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_Y (0x2U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_XY (0x3U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_Z (0x4U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_ZX (0x5U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_YZ (0x6U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_XYZ (0x7U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_XYX (0x8U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_YXY (0x9U << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_YZY (0xAU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_XZX (0xBU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_XYZ_POS_AFE (0xCU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_XYZ_NEG_AFE (0xDU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_HALL_RESISTANCE (0xEU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)
#define SENSOR_CONFIG_1_MAG_CH_EN_HALL_OFFSET (0xFU << SENSOR_CONFIG_1_MAG_CH_EN_Pos)

#define SENSOR_CONFIG_2 (0x03)
#define SENSOR_CONFIG_2_RESET_VALUE (0x00U)

#define X_THR_CONFIG (0x04)
#define X_THR_CONFIG_RESET_VALUE (0x00U)

#define Y_THR_CONFIG (0x05)
#define Y_THR_CONFIG_RESET_VALUE (0x00U)

#define Z_THR_CONFIG (0x06)
#define Z_THR_CONFIG_RESET_VALUE (0x00U)

#define T_CONFIG (0x07)
#define T_CONFIG_RESET_VALUE (0x00U)

#define T_CONFIG_T_CH_EN_Pos (0)
#define T_CONFIG_T_CH_EN_Msk (0x1U << T_CONFIG_T_CH_EN_Pos)
#define T_CONFIG_T_CH_EN T_CONFIG_T_CH_EN_Msk

#define INT_CONFIG_1 (0x08)
#define INT_CONFIG_1_RESET_VALUE (0x00U)

#define INT_CONFIG_1_MASK_INTB_Pos (0U)
#define INT_CONFIG_1_MASK_INTB_Msk (0x1U << INT_CONFIG_1_MASK_INTB_Pos)
#define INT_CONFIG_1_MASK_INTB_INT_ENABLED (0x0U << INT_CONFIG_1_MASK_INTB_Pos)
#define INT_CONFIG_1_MASK_INTB_INT_DISABLED (0x1U << INT_CONFIG_1_MASK_INTB_Pos)

#define INT_CONFIG_1_INT_MODE_Pos (2U)
#define INT_CONFIG_1_INT_MODE_Msk (0x7U << INT_CONFIG_1_INT_MODE_Pos)
#define INT_CONFIG_1_INT_MODE_0 (0x1U << INT_CONFIG_1_INT_MODE_Pos)
#define INT_CONFIG_1_INT_MODE_1 (0x2U << INT_CONFIG_1_INT_MODE_Pos)
#define INT_CONFIG_1_INT_MODE_2 (0x4U << INT_CONFIG_1_INT_MODE_Pos)

#define INT_CONFIG_1_INT_STATE_Pos (5U)
#define INT_CONFIG_1_INT_STATE_Msk (0x1U << INT_CONFIG_1_INT_STATE_Pos)
#define INT_CONFIG_1_INT_STATE_LATCH (0x0U << INT_CONFIG_1_INT_STATE_Pos)
#define INT_CONFIG_1_INT_STATE_PULSE (0x1U << INT_CONFIG_1_INT_STATE_Pos)

#define INT_CONFIG_1_THRSLD_INT_Pos (6U)
#define INT_CONFIG_1_THRSLD_INT_Msk (0x1U << INT_CONFIG_1_THRSLD_INT_Pos)
#define INT_CONFIG_1_THRSLD_INT INT_CONFIG_1_THRSLD_INT_Msk

#define INT_CONFIG_1_RSLT_INT_Pos (7U)
#define INT_CONFIG_1_RSLT_INT_Msk (0x1U << INT_CONFIG_1_RSLT_INT_Pos)
#define INT_CONFIG_1_RSLT_INT INT_CONFIG_1_RSLT_INT_Msk

#define MAG_GAIN_CONFIG (0x09)
#define MAG_GAIN_CONFIG_RESET_VALUE (0x00U)

#define MAG_OFFSET_CONFIG_1 (0x0A)
#define MAG_OFFSET_CONFIG_1_RESET_VALUE (0x00U)

#define MAG_OFFSET_CONFIG_2 (0x0B)
#define MAG_OFFSET_CONFIG_2_RESET_VALUE (0x00U)

#define I2C_ADDRESS (0x0C)
#define I2C_ADDRESS_RESET_VALUE (0x6AU)

#define DEVICE_ID (0x0D)
#define DEVICE_ID_RESET_VALUE (0x04U)

#define MANUFACTURER_ID_LSB (0x0E)
#define MANUFACTURER_ID_LSB_RESET_VALUE (0x49U)

#define MANUFACTURER_ID_MSB (0x0F)
#define MANUFACTURER_ID_MSB_RESET_VALUE (0x54U)

#define T_MSB_RESULT (0x10)
#define T_MSB_RESULT_RESET_VALUE (0x00U)

#define T_LSB_RESULT (0x11)
#define T_LSB_RESULT_RESET_VALUE (0x00U)

#define X_MSB_RESULT (0x12)
#define X_MSB_RESULT_RESET_VALUE (0x00U)

#define X_LSB_RESULT (0x13)
#define X_LSB_RESULT_RESET_VALUE (0x00U)

#define Y_MSB_RESULT (0x14)
#define Y_MSB_RESULT_RESET_VALUE (0x00U)

#define Y_LSB_RESULT (0x15)
#define Y_LSB_RESULT_RESET_VALUE (0x00U)

#define Z_MSB_RESULT (0x16)
#define Z_MSB_RESULT_RESET_VALUE (0x00U)

#define Z_LSB_RESULT (0x17)
#define Z_LSB_RESULT_RESET_VALUE (0x00U)

#define CONV_STATUS (0x18)
#define CONV_STATUS_RESET_VALUE (0x10U)

#define CONV_STATUS_POR_Pos (4)
#define CONV_STATUS_POR_Msk (0x1U << CONV_STATUS_POR_Pos)
#define CONV_STATUS_POR CONV_STATUS_POR_Msk

#define ANGLE_RESULT_MSB (0x19)
#define ANGLE_RESULT_MSB_RESET_VALUE (0x00U)

#define ANGLE_RESULT_LSB (0x1A)
#define ANGLE_RESULT_LSB_RESET_VALUE (0x00U)

#define MAGNITUDE_RESULT (0x1B)
#define MAGNITUDE_RESULT_RESET_VALUE (0x00U)

#define DEVICE_STATUS (0x1C)
#define DEVICE_STATUS_RESET_VALUE (0x10U)
/* clang-format on */

#endif /* TMAG5173_REG_H */
